language: ruby
rvm:
  - 2.4.1
env:
  - RAILS_ENV=test
before_script:
  - mysql -e 'create database SuperGomelitos_test;'
  - cp ./.travis.database.yml ./config/database.yml
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
notifications: 
  email:
  - jcubillosg@uqvirtual.edu.co
  - jdtintinagop@uqvirtual.edu.co
  on_success: always
  on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: G5ipIiNqalU801s356doZ5dO9D7IsajiEZ5P3AWUWvQeP11AYnyvCHrDKGK0rXMDoqyW63JWCj4wXpNA5LwskYrBonc4UhplmZc++wD8slRehFat/92AhGK2KMDlsEp8qTa6Q+3hL/02AY0SOVUb5KCGO6DQ8jpcw0L7bQeYRt6oLCOjjyjnWcTxqBnZ6aN3JUWk/42JOKqd1xf/n6+54WaJznujG7NFjVykn88gdQb8ld/fOqEoxng4qyx5HsLXPdEU7NeVpoYXd8IrkOBarcy3l1KwXb4Zc4y3YbRPL/WX/ENni2oOOlXfS1RaCRKTSF/UfkZWUGK5pYwmE0et1HBPQKROK3j4NEbMSychENmyVMIswxpiPEU0xOgUUTxOD36a8yOjEo0ozc4+LVfGmdXWSGUyw0JgRWzmXlrPgsf+bqap8+EkElklZLMAZ+MHIz4sPWvPhMAnEAiZ8XZXtJnGk1nfQ40m5oy/dku1UZZTQitBAY+NZl8xl7XmJhDaP8HuloLmZANxPrJuAGo4mZp5GKO4A0kR1crFq8oE9ong4cscgG24Q1LnWykJWwtZr7ZtbDffz1rxLrHMrjS19hT5h6h/Q3GZxjWW5eZkEC2wsdjd2MQpqoQ6Il3AuDr2WbNHKIXJc8n8RBsDOJsmoIRMzeyKjFVGQ2Sr3bUWq3o=
  